---
# tasks file for roles/ntp
- name: Installation of ntp service
  ansible.builtin.apt:
    name: ntp
    state: present
  register: result_install_ntp

- name: Already installed
  debug:
    msg: "ntp is already installed"
  when: result_install_ntp.changed != true

- name: Create ntp.conf file
  ansible.builtin.file:
    path: /etc/ntp.conf
    state: touch
    mode: 0644
  register: result_create_ntpconfig
  changed_when: false

- name: ntp configuration file already created
  debug:
    msg: "ntp configuration file is already created"
  when: result_create_ntpconfig.changed != true

- name: Show the ntp servers list
  debug:
    msg: "{{ item }}"
  loop: "{{ ntp_servers }}"
  loop_control:
    label: "{{ item }}"
  when: result_create_ntpconfig.changed == false

- name: Add servers in ntp configuration file
  ansible.builtin.lineinfile:
    path: "/etc/ntp.conf"
    line: "server {{ item }}"
    state: present
  loop: "{{ ntp_servers }}"
