---
# tasks file for roles/url
- name: Check url status
  ansible.builtin.uri:
    url: http://10.10.10.131
    method: GET
  ignore_errors: true
  register: result_check_url

- name: Display status message online
  debug:
    msg: "This URL is online"
  when: result_check_url.status == 200

- name: Display status message offline
  fail:
    msg: "This URL is offline"
  when: result_check_url.status != 200
