---
# tasks file for roles/apache2
- name: Installation of Apache2
  ansible.builtin.apt:
    name: apache2
    state: present
  register: result_apache2

- name: show result_apache2
  debug:
    var: result_apache2

- name: Already installed
  debug:
    msg: "Apache2 is already installed"
  when: result_apache2.changed != true

