---
# tasks file for roles/iptables
- name: Installation of iptables
  ansible.builtin.apt:
    name: iptables
    state: present
  become: yes
  register: result_install_iptables

- name: Already installed
  debug:
    msg: "iptables is already installed"
  when: result_install_iptables.changed != true

- name: Allow http with iptables
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 80
    jump: ACCEPT
  become: yes
  register: result_allow_http
  when: result_install_iptables.failed == false
